CREATE DATABASE db_agenda;

CREATE TABLE tb_usuarios (
	user_id INT PRIMARY KEY AUTO_INCREMENT,
	pecado VARCHAR(20) NOT NULL,
	nome VARCHAR(100) NOT NULL,
    usuario VARCHAR(20) NOT NULL,
    telefone VARCHAR(15),
    senha VARCHAR(20) NOT NULL
);